// AUTO-GENERATED from Godot class documentation.
// Manual overrides applied from typings-overrides/*.d.ts

/** A 2D texture filled with noise generated by a {@link Noise} object. */
declare class NoiseTexture2D extends Texture2D {
  /**
   * If `true`, the resulting texture contains a normal map created from the original noise interpreted as a bump map.
   */
  as_normal_map: boolean;
  /**
   * Strength of the bump maps used in this texture. A higher value will make the bump maps appear larger while a lower value will make them appear softer.
   */
  bump_strength: float;
  /** A {@link Gradient} which is used to map the luminance of each pixel to a color value. */
  color_ramp: Gradient | null;
  /**
   * Determines whether mipmaps are generated for this texture. Enabling this results in less texture aliasing in the distance, at the cost of increasing memory usage by roughly 33% and making the noise texture generation take longer.
   * **Note:** {@link generate_mipmaps} requires mipmap filtering to be enabled on the material using the {@link NoiseTexture2D} to have an effect.
   */
  generate_mipmaps: boolean;
  /** Height of the generated texture (in pixels). */
  height: int;
  /** Determines whether the noise image is calculated in 3D space. May result in reduced contrast. */
  in_3d_space: boolean;
  /** If `true`, inverts the noise texture. White becomes black, black becomes white. */
  invert: boolean;
  /** The instance of the {@link Noise} object. */
  noise: Noise | null;
  /**
   * If `true`, the noise image coming from the noise generator is normalized to the range `0.0` to `1.0`.
   * Turning normalization off can affect the contrast and allows you to generate non repeating tileable noise textures.
   */
  normalize: boolean;
  resource_local_to_scene: boolean;
  /**
   * If `true`, a seamless texture is requested from the {@link Noise} resource.
   * **Note:** Seamless noise textures may take longer to generate and/or can have a lower contrast compared to non-seamless noise depending on the used {@link Noise} resource. This is because some implementations use higher dimensions for generating seamless noise.
   * **Note:** The default {@link FastNoiseLite} implementation uses the fallback path for seamless generation. If using a {@link width} or {@link height} lower than the default, you may need to increase {@link seamless_blend_skirt} to make seamless blending more effective.
   */
  seamless: boolean;
  /**
   * Used for the default/fallback implementation of the seamless texture generation. It determines the distance over which the seams are blended. High values may result in less details and contrast. See {@link Noise} for further details.
   * **Note:** If using a {@link width} or {@link height} lower than the default, you may need to increase {@link seamless_blend_skirt} to make seamless blending more effective.
   */
  seamless_blend_skirt: float;
  /** Width of the generated texture (in pixels). */
  width: int;
  set_as_normal_map(value: boolean): void;
  is_normal_map(): boolean;
  set_bump_strength(value: float): void;
  get_bump_strength(): float;
  set_color_ramp(value: Gradient | null): void;
  get_color_ramp(): Gradient | null;
  set_generate_mipmaps(value: boolean): void;
  is_generating_mipmaps(): boolean;
  set_height(value: int): void;
  set_in_3d_space(value: boolean): void;
  is_in_3d_space(): boolean;
  set_invert(value: boolean): void;
  get_invert(): boolean;
  set_noise(value: Noise | null): void;
  get_noise(): Noise | null;
  set_normalize(value: boolean): void;
  is_normalized(): boolean;
  set_seamless(value: boolean): void;
  get_seamless(): boolean;
  set_seamless_blend_skirt(value: float): void;
  get_seamless_blend_skirt(): float;
  set_width(value: int): void;
}
