// AUTO-GENERATED from Godot class documentation.
// Manual overrides applied from typings-overrides/*.d.ts

/** Interface to a WebRTC peer connection. */
declare class WebRTCPeerConnection extends RefCounted {
  /**
   * Add an ice candidate generated by a remote peer (and received over the signaling server). See {@link ice_candidate_created}.
   */
  add_ice_candidate(media: string | NodePath, index: int, name: string | NodePath): int;
  /**
   * Close the peer connection and all data channels associated with it.
   * **Note:** You cannot reuse this object for a new connection unless you call {@link initialize}.
   */
  close(): void;
  /**
   * Returns a new {@link WebRTCDataChannel} (or `null` on failure) with given `label` and optionally configured via the `options` dictionary. This method can only be called when the connection is in state {@link STATE_NEW}.
   * There are two ways to create a working data channel: either call {@link create_data_channel} on only one of the peer and listen to {@link data_channel_received} on the other, or call {@link create_data_channel} on both peers, with the same values, and the `"negotiated"` option set to `true`.
   * Valid `options` are:
   * **Note:** You must keep a reference to channels created this way, or it will be closed.
   */
  create_data_channel(label: string | NodePath, options?: Dictionary): WebRTCDataChannel | null;
  /**
   * Creates a new SDP offer to start a WebRTC connection with a remote peer. At least one {@link WebRTCDataChannel} must have been created before calling this method.
   * If this functions returns {@link OK}, {@link session_description_created} will be called when the session is ready to be sent.
   */
  create_offer(): int;
  /** Returns the connection state. */
  get_connection_state(): int;
  /**
   * Returns the ICE {@link GatheringState} of the connection. This lets you detect, for example, when collection of ICE candidates has finished.
   */
  get_gathering_state(): int;
  /**
   * Returns the signaling state on the local end of the connection while connecting or reconnecting to another peer.
   */
  get_signaling_state(): int;
  /**
   * Re-initialize this peer connection, closing any previously active connection, and going back to state {@link STATE_NEW}. A dictionary of `configuration` options can be passed to configure the peer connection.
   * Valid `configuration` options are:
   */
  initialize(configuration?: Dictionary): int;
  /**
   * Call this method frequently (e.g. in {@link Node._process} or {@link Node._physics_process}) to properly receive signals.
   */
  poll(): int;
  /**
   * Sets the `extension_class` as the default {@link WebRTCPeerConnectionExtension} returned when creating a new {@link WebRTCPeerConnection}.
   */
  static set_default_extension(extension_class: string): void;
  /**
   * Sets the SDP description of the local peer. This should be called in response to {@link session_description_created}.
   * After calling this function the peer will start emitting {@link ice_candidate_created} (unless an {@link Error} different from {@link OK} is returned).
   */
  set_local_description(type_: string | NodePath, sdp: string | NodePath): int;
  /**
   * Sets the SDP description of the remote peer. This should be called with the values generated by a remote peer and received over the signaling server.
   * If `type` is `"offer"` the peer will emit {@link session_description_created} with the appropriate answer.
   * If `type` is `"answer"` the peer will start emitting {@link ice_candidate_created}.
   */
  set_remote_description(type_: string | NodePath, sdp: string | NodePath): int;

  /**
   * Emitted when a new in-band channel is received, i.e. when the channel was created with `negotiated: false` (default).
   * The object will be an instance of {@link WebRTCDataChannel}. You must keep a reference of it or it will be closed automatically. See {@link create_data_channel}.
   */
  data_channel_received: Signal<[WebRTCDataChannel]>;
  /**
   * Emitted when a new ICE candidate has been created. The three parameters are meant to be passed to the remote peer over the signaling server.
   */
  ice_candidate_created: Signal<[string, int, string]>;
  /**
   * Emitted after a successful call to {@link create_offer} or {@link set_remote_description} (when it generates an answer). The parameters are meant to be passed to {@link set_local_description} on this object, and sent to the remote peer over the signaling server.
   */
  session_description_created: Signal<[string, string]>;

  // enum ConnectionState
  /** The connection is new, data channels and an offer can be created in this state. */
  static readonly STATE_NEW: int;
  /** The peer is connecting, ICE is in progress, none of the transports has failed. */
  static readonly STATE_CONNECTING: int;
  /** The peer is connected, all ICE transports are connected. */
  static readonly STATE_CONNECTED: int;
  /** At least one ICE transport is disconnected. */
  static readonly STATE_DISCONNECTED: int;
  /** One or more of the ICE transports failed. */
  static readonly STATE_FAILED: int;
  /** The peer connection is closed (after calling {@link close} for example). */
  static readonly STATE_CLOSED: int;
  // enum GatheringState
  /** The peer connection was just created and hasn't done any networking yet. */
  static readonly GATHERING_STATE_NEW: int;
  /** The ICE agent is in the process of gathering candidates for the connection. */
  static readonly GATHERING_STATE_GATHERING: int;
  /**
   * The ICE agent has finished gathering candidates. If something happens that requires collecting new candidates, such as a new interface being added or the addition of a new ICE server, the state will revert to gathering to gather those candidates.
   */
  static readonly GATHERING_STATE_COMPLETE: int;
  // enum SignalingState
  /**
   * There is no ongoing exchange of offer and answer underway. This may mean that the {@link WebRTCPeerConnection} is new ({@link STATE_NEW}) or that negotiation is complete and a connection has been established ({@link STATE_CONNECTED}).
   */
  static readonly SIGNALING_STATE_STABLE: int;
  /**
   * The local peer has called {@link set_local_description}, passing in SDP representing an offer (usually created by calling {@link create_offer}), and the offer has been applied successfully.
   */
  static readonly SIGNALING_STATE_HAVE_LOCAL_OFFER: int;
  /**
   * The remote peer has created an offer and used the signaling server to deliver it to the local peer, which has set the offer as the remote description by calling {@link set_remote_description}.
   */
  static readonly SIGNALING_STATE_HAVE_REMOTE_OFFER: int;
  /**
   * The offer sent by the remote peer has been applied and an answer has been created and applied by calling {@link set_local_description}. This provisional answer describes the supported media formats and so forth, but may not have a complete set of ICE candidates included. Further candidates will be delivered separately later.
   */
  static readonly SIGNALING_STATE_HAVE_LOCAL_PRANSWER: int;
  /**
   * A provisional answer has been received and successfully applied in response to an offer previously sent and established by calling {@link set_local_description}.
   */
  static readonly SIGNALING_STATE_HAVE_REMOTE_PRANSWER: int;
  /** The {@link WebRTCPeerConnection} has been closed. */
  static readonly SIGNALING_STATE_CLOSED: int;
}
